import api from './client'

export function sendMessage({ session_id, topic_id, message, include_sources }) {
  const payload = {
    session_id,
    message,
    include_sources,
  };
  if (topic_id) {
    payload.topic_id = topic_id;
  }
  return api.post('/chat/message', payload).then((response) => {
    const data = response.data
    // 202: the reply is generated by a background Celery job.
    // Callers must poll getChatJob(job_id) until status === 'done'.
    if (response.status === 202 || data?.job_id) {
      return { ...data, pending: true }
    }
    return data
  })
}

/**
 * Poll the status of an async chat job (from POST /chat/message → 202).
 * Returns { job_id, status, response?, sources?, error? } where status is
 * one of: queued | running | done | failed. Throws on 404 (job expired).
 */
export function getChatJob(jobId) {
  return api.get(`/chat/job/${jobId}`).then((response) => response.data)
}

export function getHistory(sessionId, topicId = null) {
  const params = { session_id: sessionId };
  if (topicId) params.topic_id = topicId;
  return api.get(`/chat/history`, { params }).then((response) => response.data)
}

export function deleteHistory(sessionId, topicId = null) {
  const params = { session_id: sessionId };
  if (topicId) params.topic_id = topicId;
  return api.delete(`/chat/history`, { params }).then((response) => response.data)
}

export function uploadDocument(file, session_id, topic_id = null) {
  const formData = new FormData();
  formData.append('file', file);
  formData.append('session_id', session_id);
  if (topic_id) {
    formData.append('topic_id', topic_id);
  }

  return api.post('/chat/upload', formData, {
    headers: {
      'Content-Type': 'multipart/form-data',
    },
  }).then((response) => response.data);
}



export function getChatSessions() {
  return api.get('/chat/sessions').then((response) => response.data);
}

export function createChatSession(title) {
  return api.post('/chat/sessions', { title }).then((response) => response.data);
}

export function deleteChatSession(sessionId) {
  return api.delete(`/chat/sessions/${sessionId}`).then((response) => response.data);
}

